services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shreya
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=crm_site.settings
      - SECRET_KEY=django-insecure-yl*u@-ur7$58!tn6r9o69op-($n6p26)4+akbvi1hsu%n*&g50
      - DEBUG=True
      - DB_NAME=crm_db
      - DB_USER=postgres
      - DB_PASSWORD=shreya
      - DB_HOST=db
      - DB_PORT=5432
      - CSRF_TRUSTED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000

volumes:
  postgres_data: