# Generated by Django 5.2.4 on 2025-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='python', max_length=255),
            preserve_default=False,
        ),
    ]
