# Generated by Django 5.2.4 on 2025-07-29 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_course_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='first_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='last_pay_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='crm_app.lead'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='second_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='third_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='total_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='add_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='adset_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='class_type',
            field=models.CharField(blank=True, choices=[('Physical', 'Physical'), ('Online', 'Online')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.course'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='device',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='grade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_call',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_call',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='parents_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Bank Transfer', 'Bank Transfer'), ('Cheque', 'Cheque')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='post_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='previous_coding_experience',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Basic Python', 'Basic Python'), ('Intermediate C++', 'Intermediate C++'), ('Arduino', 'Arduino'), ('Some Linux', 'Some Linux'), ('Advanced Python', 'Advanced Python'), ('Basic Java', 'Basic Java'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='shift',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('WhatsApp', 'WhatsApp'), ('Facebook', 'Facebook'), ('Website', 'Website'), ('Email', 'Email'), ('Office Visit', 'Office Visit'), ('Direct Call', 'Direct Call'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Average', 'Average'), ('Followup', 'Followup'), ('Interested', 'Interested'), ('inProgress', 'In Progress'), ('Active', 'Active'), ('Closed', 'Closed'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Junk', 'Junk')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='workshop_batch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('sales_rep', 'Sales Representative')], default='sales_rep', max_length=20),
        ),
    ]
