# Generated by Django 5.2.4 on 2025-07-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_enrollment_course_enrollment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('WhatsApp/Viber', 'WhatsApp/Viber'), ('Facebook', 'Facebook'), ('Website', 'Website'), ('Email', 'Email'), ('Office Visit', 'Office Visit'), ('Direct Call', 'Direct Call'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Average', 'Average'), ('Followup', 'Followup'), ('Interested', 'Interested'), ('inProgress', 'In Progress'), ('Active', 'Active'), ('Converted', 'Converted'), ('Lost', 'Lost'), ('Junk', 'Junk')], default='New', max_length=20),
        ),
    ]
