# Generated by Django 5.2.4 on 2025-07-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_codingexperience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='previous_coding_experience',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Basic Python', 'Basic Python'), ('Intermediate C++', 'Intermediate C++'), ('Arduino', 'Arduino'), ('Some Linux', 'Some Linux'), ('Advanced Python', 'Advanced Python'), ('Basic Java', 'Basic Java'), ('Other', 'Other')], default='None', max_length=30),
        ),
        migrations.DeleteModel(
            name='CodingExperience',
        ),
    ]
