# Generated by Django 5.2.4 on 2025-07-30 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_lead_previous_coding_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='class_type',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.course'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='grade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='parents_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WhatsApp/Viber', 'WhatsApp/Viber'), ('Facebook', 'Facebook'), ('Website', 'Website'), ('Email', 'Email'), ('Office Visit', 'Office Visit'), ('Direct Call', 'Direct Call'), ('LinkedIn', 'LinkedIn'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp_number',
            field=models.CharField(max_length=30),
        ),
    ]
