# Generated by Django 5.2.4 on 2025-07-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_alter_lead_age_alter_lead_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='shift',
            field=models.CharField(blank=True, choices=[('7 A.M. - 9 A.M.', '7 A.M. - 9 A.M.'), ('8 A.M. - 10 A.M.', '8 A.M. - 10 A.M.'), ('10 A.M. - 12 P.M.', '10 A.M. - 12 P.M.'), ('11 A.M. - 1 P.M.', '11 A.M. - 1 P.M.'), ('12 P.M. - 2 P.M.', '12 P.M. - 2 P.M.'), ('2 P.M. - 4 P.M.', '2 P.M. - 4 P.M.'), ('2:30 P.M. - 4:30 P.M.', '2:30 P.M. - 4:30 P.M.'), ('4 P.M. - 6 P.M.', '4 P.M. - 6 P.M.'), ('4:30 P.M. - 6:30 P.M.', '4:30 P.M. - 6:30 P.M.'), ('5 P.M. - 7 P.M.', '5 P.M. - 7 P.M.'), ('6 P.M. - 7 P.M.', '6 P.M. - 7 P.M.'), ('6 P.M. - 8 P.M.', '6 P.M. - 8 P.M.'), ('7 P.M. - 8 P.M.', '7 P.M. - 8 P.M.')], max_length=50),
        ),
    ]
