# Generated by Django 5.2.4 on 2025-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_alter_lead_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('sales_rep', 'Sales Representative')], default='superadmin', max_length=20),
        ),
    ]
