# Generated by Django 5.2.4 on 2025-08-05 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('next_call_updated', 'Next Call Updated'), ('last_call_updated', 'Last Call Updated'), ('remarks_updated', 'Remarks Updated'), ('moved_to_trash', 'Moved to Trash'), ('restored', 'Restored from Trash'), ('enrollment_created', 'Enrollment Created')], max_length=20)),
                ('field_changed', models.CharField(blank=True, max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm_app.lead')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
